#' # Generated by roxygen2: do not edit by hand

# export(cf_blank)
# export(cf_cell_value)
# export(cf_custom_formula)
# export(cf_format)
# export(cf_gradient)
# export(cf_not_blank)
# export(cf_text_contains)
# export(cf_text_eq)
# export(gs4_color)
# export(gs4_cols)
# export(gs4_palette)
# export(gs4_palette_color)
# export(prettysheets_batch)
# export(gs_theme_clean)  # pretty_theme_clean
# export(gs_theme_fun)    # pretty_theme_fun
# export(gs_theme_professional) # pretty_theme_professional
# export(gs_theme_stylish)      # pretty_theme_stylish
# export(range_add_conditional_format)
# export(range_add_gradient_format)
# export(range_format)
# export(range_format_border)
# export(range_merge)
# export(range_unmerge)
# export(range_write_format)
# export(sheet_clear_format)
# export(sheet_format_header)
# export(sheet_format_tabcolor)
# export(sheet_freeze)

### New
# write_pretty_sheet - does the same as write_sheet but with specified formatting
# read_pretty_sheet - same as read_sheet but reads in formatting
